apiVersion: apps/v1
kind: Deployment
metadata:
  name: costsoptimizer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: costsoptimizer
  template:
    metadata:
      labels:
        app: costsoptimizer
    spec:
      containers:
      - name: costsoptimizer
        image: costsoptimizer-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
